package com.phms.mapper;

import com.phms.pojo.Standard;
import com.phms.pojo.StandardExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface StandardMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table standard
     */
    long countByExample(StandardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table standard
     */
    int deleteByExample(StandardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table standard
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table standard
     */
    int insert(Standard record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table standard
     */
    int insertSelective(Standard record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table standard
     */
    List<Standard> selectByExample(StandardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table standard
     */
    Standard selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table standard
     */
    int updateByExampleSelective(@Param("record") Standard record, @Param("example") StandardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table standard
     */
    int updateByExample(@Param("record") Standard record, @Param("example") StandardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table standard
     */
    int updateByPrimaryKeySelective(Standard record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table standard
     */
    int updateByPrimaryKey(Standard record);

    List<Standard> getAllByLimit(Standard po);

    int countAllByLimit(Standard po);
}