package com.phms.pojo;

import org.springframework.format.annotation.DateTimeFormat;

import java.util.Date;

public class Appointment extends BaseBean{
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column appointment.id
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column appointment.pet_id
     */
    private Long petId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column appointment.user_id
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column appointment.doctor_id
     */
    private Long doctorId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column appointment.app_time
     */
    @DateTimeFormat(pattern="yyyy-MM-dd HH:mm:ss")
    private Date appTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column appointment.info
     */
    private String info;
    private String phone;
    private String address;
    private String name;

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getPhone() {
        return phone;
    }

    public void setPhone(String phone) {
        this.phone = phone;
    }

    public String getAddress() {
        return address;
    }

    public void setAddress(String address) {
        this.address = address;
    }

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column appointment.create_time
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column appointment.status
     */
    private Integer status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column appointment.id
     *
     * @return the value of appointment.id
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column appointment.id
     *
     * @param id the value for appointment.id
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column appointment.pet_id
     *
     * @return the value of appointment.pet_id
     */
    public Long getPetId() {
        return petId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column appointment.pet_id
     *
     * @param petId the value for appointment.pet_id
     */
    public void setPetId(Long petId) {
        this.petId = petId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column appointment.user_id
     *
     * @return the value of appointment.user_id
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column appointment.user_id
     *
     * @param userId the value for appointment.user_id
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column appointment.doctor_id
     *
     * @return the value of appointment.doctor_id
     */
    public Long getDoctorId() {
        return doctorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column appointment.doctor_id
     *
     * @param doctorId the value for appointment.doctor_id
     */
    public void setDoctorId(Long doctorId) {
        this.doctorId = doctorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column appointment.app_time
     *
     * @return the value of appointment.app_time
     */
    public Date getAppTime() {
        return appTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column appointment.app_time
     *
     * @param appTime the value for appointment.app_time
     */
    public void setAppTime(Date appTime) {
        this.appTime = appTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column appointment.info
     *
     * @return the value of appointment.info
     */
    public String getInfo() {
        return info;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column appointment.info
     *
     * @param info the value for appointment.info
     */
    public void setInfo(String info) {
        this.info = info == null ? null : info.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column appointment.create_time
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column appointment.create_time
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column appointment.status
     *
     * @return the value of appointment.status
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column appointment.status
     *
     * @param status the value for appointment.status
     */
    public void setStatus(Integer status) {
        this.status = status;
    }
}