package com.phms.pojo;

public class Standard  extends BaseBean{
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column standard.id
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column standard.age_min
     */
    private Integer ageMin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column standard.age_max
     */
    private Integer ageMax;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column standard.temp_min
     */
    private Double tempMin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column standard.temp_max
     */
    private Double tempMax;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column standard.weight_min
     */
    private Double weightMin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column standard.weight_max
     */
    private Double weightMax;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column standard.height_min
     */
    private Double heightMin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column standard.height_max
     */
    private Double heightMax;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column standard.appetite_min
     */
    private Double appetiteMin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column standard.appetite_max
     */
    private Double appetiteMax;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column standard.type
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column standard.status
     */
    private Integer status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column standard.id
     *
     * @return the value of standard.id
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column standard.id
     *
     * @param id the value for standard.id
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column standard.age_min
     *
     * @return the value of standard.age_min
     */
    public Integer getAgeMin() {
        return ageMin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column standard.age_min
     *
     * @param ageMin the value for standard.age_min
     */
    public void setAgeMin(Integer ageMin) {
        this.ageMin = ageMin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column standard.age_max
     *
     * @return the value of standard.age_max
     */
    public Integer getAgeMax() {
        return ageMax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column standard.age_max
     *
     * @param ageMax the value for standard.age_max
     */
    public void setAgeMax(Integer ageMax) {
        this.ageMax = ageMax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column standard.temp_min
     *
     * @return the value of standard.temp_min
     */
    public Double getTempMin() {
        return tempMin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column standard.temp_min
     *
     * @param tempMin the value for standard.temp_min
     */
    public void setTempMin(Double tempMin) {
        this.tempMin = tempMin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column standard.temp_max
     *
     * @return the value of standard.temp_max
     */
    public Double getTempMax() {
        return tempMax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column standard.temp_max
     *
     * @param tempMax the value for standard.temp_max
     */
    public void setTempMax(Double tempMax) {
        this.tempMax = tempMax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column standard.weight_min
     *
     * @return the value of standard.weight_min
     */
    public Double getWeightMin() {
        return weightMin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column standard.weight_min
     *
     * @param weightMin the value for standard.weight_min
     */
    public void setWeightMin(Double weightMin) {
        this.weightMin = weightMin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column standard.weight_max
     *
     * @return the value of standard.weight_max
     */
    public Double getWeightMax() {
        return weightMax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column standard.weight_max
     *
     * @param weightMax the value for standard.weight_max
     */
    public void setWeightMax(Double weightMax) {
        this.weightMax = weightMax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column standard.height_min
     *
     * @return the value of standard.height_min
     */
    public Double getHeightMin() {
        return heightMin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column standard.height_min
     *
     * @param heightMin the value for standard.height_min
     */
    public void setHeightMin(Double heightMin) {
        this.heightMin = heightMin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column standard.height_max
     *
     * @return the value of standard.height_max
     */
    public Double getHeightMax() {
        return heightMax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column standard.height_max
     *
     * @param heightMax the value for standard.height_max
     */
    public void setHeightMax(Double heightMax) {
        this.heightMax = heightMax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column standard.appetite_min
     *
     * @return the value of standard.appetite_min
     */
    public Double getAppetiteMin() {
        return appetiteMin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column standard.appetite_min
     *
     * @param appetiteMin the value for standard.appetite_min
     */
    public void setAppetiteMin(Double appetiteMin) {
        this.appetiteMin = appetiteMin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column standard.appetite_max
     *
     * @return the value of standard.appetite_max
     */
    public Double getAppetiteMax() {
        return appetiteMax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column standard.appetite_max
     *
     * @param appetiteMax the value for standard.appetite_max
     */
    public void setAppetiteMax(Double appetiteMax) {
        this.appetiteMax = appetiteMax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column standard.type
     *
     * @return the value of standard.type
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column standard.type
     *
     * @param type the value for standard.type
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column standard.status
     *
     * @return the value of standard.status
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column standard.status
     *
     * @param status the value for standard.status
     */
    public void setStatus(Integer status) {
        this.status = status;
    }
}